# Site settings
title: "Projekt Gedankenlos"
description: "Muss Kunst perfekt sein?"
owner:
  name: Marika # or company name
  email: marika@marika
  url: "https://marika-gedankenlos.github.io/"
first_published: 2017 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marika-gedankenlos.github.io" # the base hostname & protocol for your site

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Willkommen!
  text: Schau dich gern ein bisschen um :) 
# - title for your blog's featured posts
features-title: "Neue Posts"
# - displayed at the bottom
closing-head: "Danke für deinen Besuch!"
closing-para: Feel free to get in touch. Cheers!

# on all pages (and the first three you list display with greeting, if included)
social:
  twitter: https://twitter.com/Rialein97
  facebook-official: https://www.facebook.com/marika.gedankenlos/
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/_.mari.ka._/
  youtube-square: https://www.youtube.com/channel/UCs0mxHjHOu74cFl3Vb8yFyg
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
