# Site settings
title: Projekt Gedankenlos
email: hello@marika
description: > # this means to ignore newlines until "baseurl:"
  Das hier ist mein Projekt Gedankenlos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://marika-gedankenlos.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  marika-gedankenlos

# Build settings
markdown: kramdown
